In [4]:
import pandas as pd

In [245]:
year_name = "2015"

In [246]:
df = pd.read_excel('workingcopy.xlsx', sheet_name=year_name, skiprows=5)

In [247]:
df.head()

,5,15892,MEGAN LEE CHIUSAROLI,2015/01/06,2015/01/06.1,-,-.1,N,? HIGH ALTITUDE PULMONARY EDEMA ACUTE MOUNTAIN SICKNESS,ACE THE HIMALAYA,Unnamed: 10,17632.188,SELF - PAY,Unnamed: 13
0,6,15698,OLIVIA SHERWOOD,2015/01/12,2014-12-19 00:00:00,-,-,N,UPPER RESPIRATORY TRACT INFECTION.,OUTFITTER,NaN,12966.666300,SELF- PAY,NaN
1,7,15981,ANDRII BOZHOK,2015/01/12,2015/01/12,-,-,N,ACUTE MOUNTAIN SICKNESS,-,NaN,14616.210000,SELF - PAY,NaN
2,8,15959,RACHEL BIDSTRUP,2015/01/14,2015/01/10,-,-,N,HAPE; RTI,HIMALAYAN ENCOUNTER,NaN,18640.900850,SELF - PAY,NaN
3,9,16022,LINDA AGNES AMARANTI,2015/01/15,2015/01/15,-,-,N,AMS,HIMALAYAN SOCIAL JOURNEY,NaN,9374.400000,SELF - PAY,NaN
4,10,14912,ROSS JENNINGS,2015/01/20,"2014/11/03,05,07,09,10,11",-,-,N,"FROST BITE OF FINGERS BOTH HANDS, ...",WORLD EXPEDITIONS,NaN,52423.972356,AGENT,NaN

Choices:
1. I have changed "Travel/Trekking Agency" to "पर्यटक्लाई अस्प्ताल ल्याउने उद्दार कम्पनी". I didn't know what else fit that. We could say we don't have the data, but I feel like this column sums it up best.
1. We don't have details of the helicopter companies. I don't know how we can possibly get these, but if it's not necessary, then we should just say we don't have it. We still have time, so we might be able to pull this information, but I can't be sure.
1. It seems like they want us to split things into two categories: the actual charges and the amounts we billed to the insurance companies. For "agents" like Alpine Rescue, we haven't billed any insurance company, so I have left it as 0, but the bill amount is the same amount as the "Total" in our aggregate spreadsheet.

In [248]:
df.columns = ["सि.न", "पर्यटकको नाम", "नाम", "Bill Date" , "भर्ना/OPD मिती", "डिस्चार्ज मिती", "Length of Stay", "Admitted", "उपचारको कारण", "पर्यटक्लाई अस्प्ताल ल्याउने उद्दार कम्पनी", "बीमा कम्पनी", "उपचार रकम", "Paid By", "कैफियत"]

In [249]:
df.head()

,सि.न,पर्यटकको नाम,नाम,Bill Date,भर्ना/OPD मिती,डिस्चार्ज मिती,Length of Stay,Admitted,उपचारको कारण,पर्यटक्लाई अस्प्ताल ल्याउने उद्दार कम्पनी,बीमा कम्पनी,उपचार रकम,Paid By,कैफियत
0,6,15698,OLIVIA SHERWOOD,2015/01/12,2014-12-19 00:00:00,-,-,N,UPPER RESPIRATORY TRACT INFECTION.,OUTFITTER,NaN,12966.666300,SELF- PAY,NaN
1,7,15981,ANDRII BOZHOK,2015/01/12,2015/01/12,-,-,N,ACUTE MOUNTAIN SICKNESS,-,NaN,14616.210000,SELF - PAY,NaN
2,8,15959,RACHEL BIDSTRUP,2015/01/14,2015/01/10,-,-,N,HAPE; RTI,HIMALAYAN ENCOUNTER,NaN,18640.900850,SELF - PAY,NaN
3,9,16022,LINDA AGNES AMARANTI,2015/01/15,2015/01/15,-,-,N,AMS,HIMALAYAN SOCIAL JOURNEY,NaN,9374.400000,SELF - PAY,NaN
4,10,14912,ROSS JENNINGS,2015/01/20,"2014/11/03,05,07,09,10,11",-,-,N,"FROST BITE OF FINGERS BOTH HANDS, ...",WORLD EXPEDITIONS,NaN,52423.972356,AGENT,NaN

In [250]:
index = df[["पर्यटकको नाम","नाम"]]

In [251]:
index.head()

   पर्यटकको नाम                   नाम
0         15698       OLIVIA SHERWOOD
1         15981         ANDRII BOZHOK
2         15959       RACHEL BIDSTRUP
3         16022  LINDA AGNES AMARANTI
4         14912         ROSS JENNINGS

In [252]:
index.to_excel("index" + year_name + ".xlsx")

In [253]:
df.fillna('')

,सि.न,पर्यटकको नाम,नाम,Bill Date,भर्ना/OPD मिती,डिस्चार्ज मिती,Length of Stay,Admitted,उपचारको कारण,पर्यटक्लाई अस्प्ताल ल्याउने उद्दार कम्पनी,बीमा कम्पनी,उपचार रकम,Paid By,कैफियत
0,6,15698,OLIVIA SHERWOOD,2015/01/12,2014-12-19 00:00:00,-,-,N,UPPER RESPIRATORY TRACT INFECTION.,OUTFITTER,,12966.666300,SELF- PAY,
1,7,15981,ANDRII BOZHOK,2015/01/12,2015/01/12,-,-,N,ACUTE MOUNTAIN SICKNESS,-,,14616.210000,SELF - PAY,
2,8,15959,RACHEL BIDSTRUP,2015/01/14,2015/01/10,-,-,N,HAPE; RTI,HIMALAYAN ENCOUNTER,,18640.900850,SELF - PAY,
3,9,16022,LINDA AGNES AMARANTI,2015/01/15,2015/01/15,-,-,N,AMS,HIMALAYAN SOCIAL JOURNEY,,9374.400000,SELF - PAY,
4,10,14912,ROSS JENNINGS,2015/01/20,"2014/11/03,05,07,09,10,11",-,-,N,"FROST BITE OF FINGERS BOTH HANDS, ...",WORLD EXPEDITIONS,,52423.972356,AGENT,
5,11,15521,LUCY POTE,2015/01/20,2014/12/06,2014/12/08,2,Y,HIGH ALTITUDE CEREBRAL OEDEMA (HACE),C/O ALPINE RESCUE SERVICE,C/O ALPINE RESCUE SERVICE,138617.310000,AGENT,
6,12,15117,FELIPE MOSCON,2015/01/20,2014/11/13,2014/11/14,1,Y,ACUTE MOUNTAIN SICKNESS/ HIGH ALTITUDE CE...,,TRAVEL INSURANCE DIRECT,88308.515824,AGENT,
7,13,15084,SUSANNA BRANDI,2015/01/20,2014/11/12,2014-11-14 00:00:00,2,Y,ACUTE MOUNTAIN SICKNESS / ACUTE BACTERIA...,HIMALALYAN SOCIAL JOURNEY,ALPINE RESCUE,170888.873018,INSURANCE,
8,14,15188,TRENT HOPKINS,2015/01/20,2014/11/17,-,-,N,HIGH ALTITUDE CEREBRAL EDEMA- RESOLVING,ALPINE RESCUE SERVICE,ALPINE RESCUE SERVICE.,4889.140000,AGENT,
9,15,16111,EDWINNA COMBES,2015/01/23,2015/01/23,-,-,N,URTI/ AMS.,OUTFITTER NEPAL,,22383.660600,SELF - PAY,
10,16,15675,JACOBUS HERCULES DE LA REY,2015/01/26,2014/12/18,2014/12/19,-,Y,ACUTE MOUNTAIN SICKNESS WITH DEHYDRATION\n...,,KATHMANDU TRAVELS,103677.350838,AGENT,
11,17,15419,FLORENCE AULAGNER,2015/01/26,2014/11/29,2014/12/02,3,Y,HAPE\nRESPIRATORY TRACT INFECTION\n(...,GLACIER SAFARI TREK,KATHMANDU TRAVELS.,217201.554504,AGENT,
12,18,14793,RUBEN MAGARELLI,2015/01/26,2014/10/28 '2014/10/31 '2014/11/02,2014/10/29,1,N,Frost Bite of Bilateral Feets (grade 2...,HAPPY FEET MOUNTAINEERS,KATHMANDU TRAVELS AND TOURS,51633.670000,AGENT,
13,19,15220,YHONATAN LEVI,2015/01/27,2014/11/18,2014/11/19,1,Y,,YELLOW SWISSA,INTERNATIONAL MEDICAL ASSISTANCE,38935.596138,INSURANCE,
14,20,16160,GAGAN DEEP SINGH,2015/01/27,2015/01/27,-,-,N,HIGH ALTITUDE PULMONARY EDEMA.\nHIGH ALTITUDE ...,-,-,20575.800000,SELF - PAY,
15,21,16164,LAURA BLACKMORE,2015/01/28,2015/01/27,-,-,N,ACUTE MOUNTAIN SICKNESS.\nHIGH ALTITUDE PULMON...,AROUND GOOD PEOPLE,,17517.254580,SELF - PAY,
16,22,16204,MAKOTO HOSOKAWA,2015/01/30,2015/01/30,-,-,N,AMS,,,9325.260000,SELF - PAY,
17,23,16287,ANNE DEICHMANN NIELSEN,2015/02/06,2015/02/06,-,-,N,ACUTE BACTERIAL DIARRHEA.\n,GOUDA,,25003.087200,SELF - PAY,
18,24,14853,CHARLOTTE NYGAARD,2015/02/09,2014/10/31 '2014/11/03,2014/11/01,1,Y,ACUTE MOUNTAIN SICKNESS\nHIGH ALTITUDE ...,-,ALPINE,108757.219914,AGENT,
19,25,15029,BENJAMIN OTTO SWINGLER,2015/02/09,"2014/11/08, 10",-,-,N,"NON CARDIOGENIC CHEST PAIN, CHEST PAIN SEC...",KIPLING TRAVEL,ALPINE RESCUE SERVICES,25666.095546,AGENT,
20,26,15316,EMMA KATRINE TOFT BEHNCKE,2015/02/09,2014/11/23,2014/11/25,2,Y,ACUTE MOUNTAIN SICKNESS WITH ACUTE BAC...,GAP ADVENTURE PROGRAMME PVT. LTD,ALPINE,155943.212614,AGENT,
21,27,15315,NIS KRISTIAN NIELSEN,2015/02/09,2014/11/23,-,-,N,ACUTE BACTERIAL DIARRHEA WITH MILD DEHYDRATI...,GAP ADVENTURE PROGRAMME PVT. LTD,ALPINE RESCUE SERVICE PVT. LTD,14724.612263,AGENT,
22,28,15530,ROSLYN CHAN,2015/02/09,2014/12/07,2014/12/08,1,Y,ACUTE MOUNTAIN SICKNESS\nUPPER RESPIRATORY ...,OUTFITTER NEPAL,ALPINE RESCUE,90306.629196,AGENT,
23,29,15763,ELIZABETH EDWARDS,2015/02/09,2014/12/25,-,-,N,ACUTE MOUNTAIN SICKNESS/ HIGH ALTITUDE CEREBR...,ALPINE RESCUE,COVER MORE TRAVEL INSURANCE,27980.609160,AGENT,
24,30,16514,SARAH MITCHELL,2015/02/23,2015/02/23,-,-,N,AMS/ HACE,-,-,22847.170500,SELF - PAY,
25,31,16551,JENNY BEAK VEDDENG,2015/02/25,2015/02/24,-,-,N,RIGHT HIP PAIN,,,16960.666800,SELF,
26,32,16566,JASON FLETCHER,2015/02/26,2015/02/26,-,-,N,LEFT KNEE PAIN,INTREPID,,14530.959885,SELF,
27,33,16665,MARC BAEHNI,2015/03/04,2015/03/04,-,-,N,ACUTE MOUNTAIN SICKNESS,,,14517.720000,SELF,
28,34,16668,NOBUMITSU TAKASHIMA,2015/03/04,2015/03/04,-,-,N,ACUTE MOUNTAIN SICKNESS,,,9332.820000,SELF,
29,35,16058,LAURA HELEN ARMSTRONG,2015/03/04,2015/01/19,2015/01/20,1,Y,ACUTE MOOUNTAIN SICKNESS ACUTE MOOUNTAI...,HIMALAYAN ENCOUNTERS,ALPINE,113616.664320,AGENT,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,248,19643,MAY BLOCH,2015/11/18,2015/11/18,-,-,N,PATELLO- FEMORAL PAIN SYNDROME,HIMALAYAN EXPEDITION,,18135.199089,Self,
243,249,19317,ANN ELISABETH PRICE,2015/11/19,2015/10/26,2015/10/27,1,Y,SYNCOPE- CARDIOGENIC WITH ACS (ACUTE CO...,SUMMIT NEPAL TREKKING,,279991.540404,Self,
244,250,19668,CHERYL HOLMAN,2015/11/20,2015/11/19,2015/11/20,1,Y,"ACUTE BACTERIAL DIARRHEA.\nACUTE MOUNTAIN,SICK...",,,98933.717884,Self,
245,251,19665,JEAN-YVES MALADRY,2015/11/22,2015/11/22,-,-,N,ACUTE MOUNTAIN SICKNESS,C/O SHERPA AND SWISS ADVENTURE,,38940.993000,"Consult on 2015/11/19, F/U On 2015/11/20",
246,252,19727,SIMON LAIRD,2015/11/26,2015/11/26,-,-,N,ACUTE MOUNTAIN SICKNESS\nHIGH ALTITUDE PULMONA...,MACTREK AND EXPEDITION,ALPINE RESCUE,21333.312000,,"Not sure who paid the bill, alpine rescue or i..."
247,253,19745,KIN CHEUK TSANG,2015/11/27,2015/11/27,-,-,N,injury right ankle,,,18217.548000,Self,
248,254,19223,ROGER FLOOD,2015/11/30,2015/10/19,2015/10/20,1,Y,ACUTE MOUNTAIN SICKNESS WITH DEHYD...,HIMALAYA EXPEDITION,ALPINE RESCUE,143633.506664,Agent,
249,255,19435,JOSEPH ISAIA,2015/11/30,2015/11/02,2015/11/03,1,Y,HIGH ALTITUDE PULMONARY OEDEMA\nMILD HIGH ALT...,,ALPINE RESCUE,195534.298682,Agent,Also includes F/U on 2015/11/04
250,256,19133,TONI SUNOL,2015/11/30,2015/10/12,2015/10/13,1,Y,ACUTE MOUNTAIN SICKNESS\nHIGH ALTITUDE CEREBR...,WORL EXPENDITIONS,ALPINE RESCUE,110866.665772,Agent,Also includes F/U on 2015/10/14
251,257,19256,STEIN ARVE BERNES,2015/11/30,2015/11/30,-,-,N,ACUTE MOUNTAIN SICKNESS\nLIKELY HIGH ALTITUD...,ALPINE RESCUE SERVICE,ALPINE RESCUE SERVICE,12459.644400,Agent,
252,258,19379,SEAN KONINGS,2015/11/30,2015/11/30,-,-,N,FRACTURE TIP LATERAL MALLEOUS/ GRADE...,ASCENT HIMALYA,ALPINE RESCUE,90542.714536,,
253,259,19495,SARAH JEAN VENESS,2015/11/30,2015/11/06,2015/11/10,4,Y,"DIABETES MELLITUS TYPE 1, DIABETIC KETOACID...",ALPINE RESCUE,ALPINE RESCUE,662669.580076,Agent,
254,260,19817,BYNDIE SHAIE WARRICK,2015/12/05,2015/12/05,-,-,N,ELBOW JOINT INJURY.,MAKALU ADV.,,20051.099731,Self,
255,261,19823,DANDI SHERPA,2015/12/05,2015/12/05,-,-,N,"HACE, AMS",HOLY SHERPA VISION TREK,,24519.568500,Self,
256,262,19818,HENDRIKUS GEORGE VAN HOOIJDONK,2015/12/05,2015/12/05,-,-,N,WEB. B. FRACTURE. FIBULA (LEFT ANKLE),ADVENT HIMALAYA TREKS,,71144.485007,Self,
257,263,19848,MEI MEI HO,2015/12/09,2015/12/09,-,-,N,ACUTE MOUNTAIN SICKNESS,NEPAL TREKING COMPANY,,20577.732000,Self,
258,264,17032,TORE SUNDE-RASMUSSEN,2015/12/10,2015/12/10,-,-,N,AMS/ HACE,ASCENT HIMALAYAS TREK & EXP. PVT. LTD,ALPINE RESCUE,32359.908000,????,"Not sure who paid the bill, alpine rescue or p..."
259,265,19892,MOHAMED ZAHARAN LIYABDEEN,2015/12/16,2015/12/16,-,-,N,PAIN CHEST (L) ? MUSCULOSKELETAL,,,23223.888244,Self,
260,266,19341,NAWRAJ PRADHAN,2015/12/16,2015/12/16,-,-,N,FISH TAIL- AMBULANCE PICKUP FROM AIRPORT TO...,,CIGNA,47326.918800,Insurance,
261,267,19651,BENEDICTE JOUBERT,2015/12/18,2015/11/18,2015/11/20,2,Y,SUBCUTANEOUS HEMATOMA RIGHT ...,MUTUAIDE / ADVENTURE 6000,,223742.456277,Agent,
262,268,19491,DANIEL CAILLAULT,2015/12/18,2015/11/06,2015/11/07,1,Y,ACUTE LEFT KNEE INJURY\n(SERVICE PROVIDE...,ADV 6000,ADVENTURE 6000,145671.588966,Agent,
263,269,19577,SIRPA MARIA KATARINA KINNARI,2015/12/18,2015/11/12,2015/11/16,4,Y,HIGH ALTITUDE PULMONARY EDEMA\n...,,ALPINE RESCUE,597341.813377,Agent,
264,270,19444,RUDI MIKALSEN,2015/12/18,2015/11/03,2015/11/05,2,Y,"HIGH ALTITUDE PULMONARY EDEMA, PROBABLE ...",ALPINE RESCUE,ALPINE RESCUE,198156.796415,Agent,Includes F/U on 2015/11/09
265,271,19245,BARBARA LENGS,2015/12/18,2015/10/21,2015/10/24,3,Y,EROSIVE GASTRITIS WITH DUODENAL U...,,ALPINE RESCUE,303989.989077,Agent,
266,272,19615,DAMIANO GIANNI CANIGLIA,2015/12/18,2015/11/16,2015/11/20,4,Y,"SEVERE BACK PAIN, PROLAPSE...",SOCIAL TOURS,ALPINE RESCUE,369040.804608,Agent,
267,273,19968,JOANNA MURPHY,2015/12/25,2015/12/24,2015/12/25,1,Y,ACUTE MOUNTAIN SICKNESS/ UPPER...,WORLD EXPEDITIONS,,142390.444632,Self,
268,274,19401,MINGMA GYALJE SHERPA,2015/12/28,2015/12/28,-,-,N,"FROST BITE , SOFT TISSUE INJURY",DREAMERS DESTINATION TREK,,17758.057590,Self,"Consult on 2015/10/31, F/U on 2015/11/05"
269,275,19987,BENJAMIN NOVELL,2015/12/28,2015/12/28,-,-,N,"URTI, DEHYDRATION",HIMALAYAN ENCOUNTER,,39190.105356,Self,
270,276,19988,YUMI CHO,2015/12/28,2015/12/28,-,-,N,CONTACT DERMATITIS,SIMRIK REAL NEPAL TREKS,,12402.072616,Self,
271,277,20006,BOWEN LIN,2015/12/31,2015/12/31,-,-,N,AMS,,,26580.624000,Self,

In [254]:
import numpy as np

In [255]:
df["Paid By"] = df["Paid By"].str.lower()

In [256]:
df["Paid By"] = df["Paid By"].str.strip()

In [257]:
ins = df["Paid By"] == "insurance"

In [258]:
df["बीमा दाबी रकम"] = df["उपचार रकम"][ins]

In [259]:
df.head()

,सि.न,पर्यटकको नाम,नाम,Bill Date,भर्ना/OPD मिती,डिस्चार्ज मिती,Length of Stay,Admitted,उपचारको कारण,पर्यटक्लाई अस्प्ताल ल्याउने उद्दार कम्पनी,बीमा कम्पनी,उपचार रकम,Paid By,कैफियत,बीमा दाबी रकम
0,6,15698,OLIVIA SHERWOOD,2015/01/12,2014-12-19 00:00:00,-,-,N,UPPER RESPIRATORY TRACT INFECTION.,OUTFITTER,NaN,12966.666300,self- pay,NaN,NaN
1,7,15981,ANDRII BOZHOK,2015/01/12,2015/01/12,-,-,N,ACUTE MOUNTAIN SICKNESS,-,NaN,14616.210000,self - pay,NaN,NaN
2,8,15959,RACHEL BIDSTRUP,2015/01/14,2015/01/10,-,-,N,HAPE; RTI,HIMALAYAN ENCOUNTER,NaN,18640.900850,self - pay,NaN,NaN
3,9,16022,LINDA AGNES AMARANTI,2015/01/15,2015/01/15,-,-,N,AMS,HIMALAYAN SOCIAL JOURNEY,NaN,9374.400000,self - pay,NaN,NaN
4,10,14912,ROSS JENNINGS,2015/01/20,"2014/11/03,05,07,09,10,11",-,-,N,"FROST BITE OF FINGERS BOTH HANDS, ...",WORLD EXPEDITIONS,NaN,52423.972356,agent,NaN,NaN

In [260]:
submit = df[["सि.न","पर्यटकको नाम", "भर्ना/OPD मिती", "डिस्चार्ज मिती", "उपचारको कारण", "उपचार रकम","बीमा दाबी रकम", "पर्यटक्लाई अस्प्ताल ल्याउने उद्दार कम्पनी", "कैफियत"]]

In [261]:
submit.head()

,सि.न,पर्यटकको नाम,भर्ना/OPD मिती,डिस्चार्ज मिती,उपचारको कारण,उपचार रकम,बीमा दाबी रकम,पर्यटक्लाई अस्प्ताल ल्याउने उद्दार कम्पनी,कैफियत
0,6,15698,2014-12-19 00:00:00,-,UPPER RESPIRATORY TRACT INFECTION.,12966.666300,NaN,OUTFITTER,NaN
1,7,15981,2015/01/12,-,ACUTE MOUNTAIN SICKNESS,14616.210000,NaN,-,NaN
2,8,15959,2015/01/10,-,HAPE; RTI,18640.900850,NaN,HIMALAYAN ENCOUNTER,NaN
3,9,16022,2015/01/15,-,AMS,9374.400000,NaN,HIMALAYAN SOCIAL JOURNEY,NaN
4,10,14912,"2014/11/03,05,07,09,10,11",-,"FROST BITE OF FINGERS BOTH HANDS, ...",52423.972356,NaN,WORLD EXPEDITIONS,NaN

In [262]:
submit.to_excel(year_name + "submission.xlsx")